// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD56hUS3m8FefYCYzuBO9_z9Li20BvYlKI',
    appId: '1:362539034942:web:139a81ef889fe20b9aa46f',
    messagingSenderId: '362539034942',
    projectId: 'smart-home-iot-codreanu-dan',
    authDomain: 'smart-home-iot-codreanu-dan.firebaseapp.com',
    databaseURL: 'https://smart-home-iot-codreanu-dan-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-home-iot-codreanu-dan.appspot.com',
    measurementId: 'G-F395W668JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTJFkYM3LKEt1isl3R7R2fHe7vvhv9LBE',
    appId: '1:362539034942:android:9d62b9b3d71f418b9aa46f',
    messagingSenderId: '362539034942',
    projectId: 'smart-home-iot-codreanu-dan',
    databaseURL: 'https://smart-home-iot-codreanu-dan-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-home-iot-codreanu-dan.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD56hUS3m8FefYCYzuBO9_z9Li20BvYlKI',
    appId: '1:362539034942:web:f80ac2a72cb402da9aa46f',
    messagingSenderId: '362539034942',
    projectId: 'smart-home-iot-codreanu-dan',
    authDomain: 'smart-home-iot-codreanu-dan.firebaseapp.com',
    databaseURL: 'https://smart-home-iot-codreanu-dan-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-home-iot-codreanu-dan.appspot.com',
    measurementId: 'G-V8B4R36D8H',
  );
}
